.\"                                      Hey, EMACS: -*- nroff -*-
.TH FOO-YC20 1 "December  9, 2010"
.SH NAME
foo-yc20 \- YC-20 organ emulation
.SH SYNOPSIS
.B foo-yc20
.SH DESCRIPTION
The YC-20 is a divide-down combo organ designed in the late 60's. This
emulation faithfully copies the features, sounds and flaws of the original
organ.
.SH AUTHOR
foo-yc20 was written by Sampo Savolainen <v2@iki.fi>.
.PP
This manual page was written by Alessandro Ghedini <al3xbio@gmail.com>,
for the Debian project (and may be used by others).
